#!/usr/bin/python

import urllib2
from pattern.web import Twitter, plaintext




proxy = urllib2.ProxyHandler({'http':'http://n0083510:1976slHb@www-proxy:80'})
opener = urllib2.build_opener(proxy,urllib2.HTTPHandler)
urllib2.install_opener(opener)





for tweet in Twitter().search('"dover"', cached=False):
   print plaintext(tweet.description)





"""
response = urllib2.urlopen('http://python.org/')
html = response.read()
print html
"""

